<?php

namespace App\Helpers;


class Constants {
    const GAME_STAGE_1 = 'GAME_STAGE_1';
    const GAME_STAGE_2 = 'GAME_STAGE_2';
    const GAME_STAGE_3 = 'GAME_STAGE_3';
    const GAME_STAGE_4 = 'GAME_STAGE_4';
}

class ErrorConstants {
    const GAME_NOT_CREATED = 'GAME_NOT_CREATED';
    const GAME_NOT_FOUND = 'GAME_NOT_FOUND';
    const GAME_USERS_COUNT_MISMATCH = 'GAME_USERS_COUNT_MISMATCH';
    const GAME_HAS_FINISHED = 'GAME_HAS_FINISHED';
    const GAME_HAS_ACTIVE_QUESTION = 'GAME_HAS_ACTIVE_QUESTION';
    const GAME_DONT_HAVE_ACTIVE_QUESTION = 'GAME_DONT_HAVE_ACTIVE_QUESTION';
    const GAME_NOT_ALL_USERS_ANSWERED = 'GAME_NOT_ALL_USERS_ANSWERED';
    const NO_QUESTIONS_LEFT = 'NO_QUESTIONS_LEFT';
    const HIDDEN_QUESTION = 'HIDDEN_QUESTION';
    const BOX_IS_OWNED = 'BOX_IS_OWNED';
    const USER_CANNOT_ATTACK_OWN_BOX = 'USER_CANNOT_ATTACK_OWN_BOX';
    const NO_COMPETITIVE_BOX_EXISTS = 'NO_COMPETITIVE_BOX_EXISTS';
    const CANNOT_DELETE_BOX = 'CANNOT_DELETE_BOX';
    const ANOTHER_USER_SHOULD_MOVE = 'ANOTHER_USER_SHOULD_MOVE';
    const ANOTHER_USER_SHOULD_ANSWER = 'ANOTHER_USER_SHOULD_ANSWER';
    const NO_USER_MOVE_EXISTS = 'NO_USER_MOVE_EXISTS';
    const USER_ALREADY_ANSWERED_TO_QUESTION = 'USER_ALREADY_ANSWERED_TO_QUESTION';
    const USER_CANNOT_SET_BASE = 'USER_CANNOT_SET_BASE';
    const USER_TRIES_TO_REMOVE_BASE = 'USER_TRIES_TO_REMOVE_BASE';
    const USER_ALREADY_SET_BASE = 'USER_ALREADY_SET_BASE';
    const USER_CANNOT_MOVE_TO_BOX = 'USER_CANNOT_MOVE_TO_BOX';
    const COMPETITIVE_WINNER_NOT_FOUND = 'COMPETITIVE_WINNER_NOT_FOUND';
    const COMPETITIVE_WINNER_BOX_NOT_FOUND = 'COMPETITIVE_WINNER_BOX_NOT_FOUND';
    const NO_GAME_STAGE_FOUND = 'NO_GAME_STAGE_FOUND';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
}